name: github_action
on: 
  push:
      branches:
        - main
permissions:
  id-token: write
  contents: read
jobs:
  terraform-init-plan:
    runs-on: self-hosted
    working-directory: ./env/dev
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          
      - name: Verify Terraform
        run: terraform version
        
      - name: Checkout
        uses: actions/checkout@v5.0.0
          
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ead40969-5353-4a27-8d19-fe7ba6c0529b
          tenant-id: 5b7c8b3b-1d7e-43cc-89e0-a64be7ba6943
          subscription-id: a3a2627e-fe07-4b90-85fb-a59dc55c5c9a
      - name: terraform init
        run: terraform init
